name: launch library list
on:
  schedule:
    - cron: '0 0 * * *' # Run every night at midnight
  workflow_dispatch:
jobs:
  scrape:
    runs-on: ubuntu-latest
    steps:
      - name: Checking out repo
        uses: actions/checkout@v3
        with:
          ref: results # Checkout the "results" branch
      - name: Setting up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'
      - name: Removing previous chrome instances on runner 
        run: sudo apt purge google-chrome-stable  
      
      - name: Download Google Chrome
        run: wget https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb
      
      - name: Install Google Chrome
        run: sudo dpkg -i google-chrome-stable_current_amd64.deb
      
      - name: Fix missing dependencies
        run: sudo apt-get install -f

      - name: Delete Google Chrome .deb file
        run: rm google-chrome-stable_current_amd64.deb
        
      # Need to fetch reqs if needed
      - name: Installing all necessary packages
        run: pip install chromedriver-autoinstaller selenium pyvirtualdisplay
      - name: Install xvfb
        run: sudo apt-get install xvfb
      
      - name: Running Python script - library_list
        env:
          USERNAME1: ${{ secrets.USERNAME1 }}
          USERNAME2: ${{ secrets.USERNAME2 }}
          USERNAME3: ${{ secrets.USERNAME3 }}
          PASSWORD1: ${{ secrets.PASSWORD1 }}
          PASSWORD2: ${{ secrets.PASSWORD2 }}
          PASSWORD3: ${{ secrets.PASSWORD3 }}
        run: python library_list.py

      - name: Check for changes
        id: check_changes
        run: |
          echo "changes=false" >> $GITHUB_ENV
          git diff --exit-code || echo "changes=true" >> $GITHUB_ENV

      - name: Commit and Push The Results From Python Selenium Action
        if: env.changes == 'true'
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add -A
          git commit -m "GitHub action -> results added"
          git push
          
